In [83]:
import random
import numpy as np

# Variant 7 tasks: 3, 4, 5, 6, 7, 8, 9, 13, 19

## Task 3:

Вводяться 4 числа n, m, r, c. Вивести масив розміру n×m, в якому в кожному рядку з номером r і в кожному стовпчику з номером c стоять 0, а інші елементи дорівнюють 1.

In [84]:
def task_3_numpy(n, m, r, c):
    res = np.ones((n, m), dtype=int)
    res[::r, :] = 0
    res[:, ::c] = 0 
    return res

def task_3_iterative(n, m, r, c):
    return [[1 if i%r and j%c else 0 for j in range(0, m)] for i in range(0, n)]

print(task_3_numpy(6, 7, 2, 3))
print(np.array_equal(task_3_numpy(200, 300, 4, 5), task_3_iterative(200, 300, 4, 5)))

%timeit -n 100 -r 10 task_3_numpy(200, 300, 4, 5)
%timeit -n 100 -r 10 task_3_iterative(200, 300, 4, 5)

[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]
True
8.91 µs ± 256 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
2.36 ms ± 48.3 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


## Task 4:

Вводяться числа n і m. Вивести масив розміру n×m, в якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0 до m–1, а всі інші елементи матриці дорівнюють 0.

In [85]:
def task_4_numpy(n, m):
    res = np.zeros((n, m), dtype=int)
    res[0] = np.arange(m, dtype=int)
    return res

def task_4_iterative(n, m):
    res = [[0] * m] * n
    res[0] = [i for i in range(m)]
    return res

print(task_4_numpy(3, 4))
print(np.array_equal(task_4_numpy(200, 300), task_4_iterative(200, 300)))

%timeit -n 100 -r 10 task_4_numpy(200, 300)
%timeit -n 100 -r 10 task_4_iterative(200, 300)

[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]
True
3.7 µs ± 546 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
5.13 µs ± 68.1 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)


## Task 5:

Вводиться число n. Вивести масив розміру n×n, в якому в рядках з парними індексами стоять 1, а в інших – 0.

In [86]:
def task_5_numpy(n, m):
    arr = np.zeros((n, m), dtype=int)
    arr[1::2] = 1
    return arr
    
def task_5_iterative(n, m):
    return [[1 if i%2 else 0 for _ in range(0, m)] for i in range(0, n)]

print(task_5_numpy(6, 7))
print(np.array_equal(task_5_numpy(200, 300), task_5_iterative(200, 300)))

%timeit -n 100 -r 10 task_5_numpy(200, 300)
%timeit -n 100 -r 10 task_5_iterative(200, 300)

[[0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1]]
True
5.5 µs ± 432 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
1.65 ms ± 26.7 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


## Task 6:

З клавіатури вводиться масив. Замінити всі ненульові елементи на –1.

In [33]:
def task_6_numpy(array):
    arr = np.array(array)
    arr[arr != 0] = -1
    return arr
    
def task_6_iterative(array):
    for i in range(len(array)):
        if array[i] != 0:
            array[i] = -1
    return array

arr = np.arange(-100, 100)

print(np.array_equal(task_6_numpy([1,0,2,0,3,0]), [-1,0,-1,0,-1,0]))
print(np.array_equal(task_6_numpy(arr), task_6_iterative(arr)))

%timeit -n 100 -r 10 task_6_numpy(arr)
%timeit -n 100 -r 10 task_6_iterative(arr)

True
True
3.59 µs ± 653 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
35.2 µs ± 3.17 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


## Task 7:

З клавіатури вводиться масив. Замінити всі нульові елементи на –1.

In [34]:
def task_7_numpy(array):
    arr = np.array(array)
    arr[arr == 0] = -1
    return arr
    
def task_7_iterative(array):
    for i in range(len(array)):
        if array[i] == 0:
            array[i] = -1
    return array

arr = np.arange(-100, 100)

print(np.array_equal(task_7_numpy([1,0,2,0,3,0]), [1,-1,2,-1,3,-1]))
print(np.array_equal(task_7_numpy(arr), task_7_iterative(arr)))

%timeit -n 100 -r 10 task_7_numpy(arr)
%timeit -n 100 -r 10 task_7_iterative(arr)

True
True
2.35 µs ± 1.25 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)
21.6 µs ± 1.67 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


## Task 8:

З клавіатури вводиться масив. Підрахувати в ньому кількість нульових та ненульових елементів.

In [89]:
def task_8_numpy(array):
    arr = np.array(array)
    nonzero_count = np.count_nonzero(arr)
    return arr.size - nonzero_count, nonzero_count
    
def task_8_iterative(array):
    nonzero_count = 0
    for i in range(len(array)):
        if array[i] != 0:
            nonzero_count += 1
    return len(array) - nonzero_count, nonzero_count

arr = np.arange(-100, 100)

print(np.array_equal(task_8_numpy([1,0,2,0,3,0,0]), (4, 3)))
print(np.array_equal(task_8_numpy(arr), task_8_iterative(arr)))

%timeit -n 100 -r 10 task_8_numpy(arr)
%timeit -n 100 -r 10 task_8_iterative(arr)

True
True
The slowest run took 4.23 times longer than the fastest. This could mean that an intermediate result is being cached.
1.63 µs ± 896 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
26.5 µs ± 1.18 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


## Task 9:

Вводиться число n. Створити масив значень від n до 0.

In [90]:
def task_9_numpy(n):
    return np.arange(n, -1, -1)
    
def task_9_iterative(n):
    return [i for i in range(n, -1, -1)]

print(np.array_equal(task_9_numpy(5), [5,4,3,2,1,0]))
print(np.array_equal(task_9_numpy(200), task_9_iterative(200)))

%timeit -n 100 -r 10 task_9_numpy(200)
%timeit -n 100 -r 10 task_9_iterative(200)

True
True
The slowest run took 4.12 times longer than the fastest. This could mean that an intermediate result is being cached.
764 ns ± 530 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
3.07 µs ± 84.7 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)


## Task 13:

Розмістити на полі 8×8 нулі та одиниці в шахматному порядку, використовуючи функцію повторення.

In [91]:
def task_13_numpy():
    board = np.array([[1, 0] * 4, [0, 1] * 4] * 4, dtype=int)
    return board

def task_13_iterative():
    board = [[None] * 8 for _ in range(8)]
    for i in range(8):
        for j in range(8):
            if (i + j) % 2 == 0:
                board[i][j] = 1
            else:
                board[i][j] = 0
    return board

print(task_13_numpy())
print(np.array_equal(task_13_numpy(), task_13_iterative()))

%timeit -n 100 -r 10 task_13_numpy()
%timeit -n 100 -r 10 task_13_iterative()


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
True
3.34 µs ± 245 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
5.01 µs ± 396 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)


## Task 19:

Згенерувати вектор із n елементів, що рівномірно розміщені на інтервалі (0,1) – тобто обидва кінці інтервалу не включені. Значення вивести до 3 знаків після коми.

In [92]:
def task_19_numpy(n):
    vec = np.random.uniform(0, 1, n)
    return np.around(vec, 3)

def task_19_iterative(n):
    vec = []
    for i in range(n):
        vec.append(round(random.uniform(0, 1), 3))
    return vec

print(task_19_numpy(10))
print(task_19_iterative(10))

%timeit -n 100 -r 10 task_19_numpy(100)
%timeit -n 100 -r 10 task_19_iterative(100)

[0.822 0.371 0.871 0.535 0.241 0.589 0.111 0.153 0.503 0.33 ]
[0.644, 0.832, 0.359, 0.746, 0.223, 0.275, 0.466, 0.776, 0.693, 0.306]
12.6 µs ± 822 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
48 µs ± 963 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
